"""Spacing and component size tokens (px equivalents)."""

from lumi.ui.theme.scale import scaled as s

SPACE_XS = s(4)
SPACE_SM = s(8)
SPACE_MD = s(16)
SPACE_LG = s(24)
SPACE_XL = s(32)

# Poster column — fixed share of horizontal space (matches original 37% layout).
POSTER_LAYOUT_STRETCH = 37
LIST_LAYOUT_STRETCH = 63

# Normalized poster crop size
POSTER_REFERENCE_WIDTH = 720
POSTER_REFERENCE_HEIGHT = 1080

# Poster placeholder styling — not scaled with library chrome.
POSTER_PLACEHOLDER_FONT_SIZE = 20
POSTER_PLACEHOLDER_PADDING = 24

ICON_SIZE = s(24)
ICON_SIZE_SM = s(16)
ICON_GAP_MD = s(12)
ICON_GAP_SM = s(4)
DIVIDER_HEIGHT = s(16)
CORNER_RADIUS_SM = s(4)

DRAWER_WIDTH = s(280)
ALPHABET_COLUMN_WIDTH = s(28)
ALPHABET_COLUMN_HEIGHT = s(500)
ALPHABET_LETTER_SIZE = s(28)
ALPHABET_FADE_HEIGHT = s(44)
ALPHABET_WRAPPER_LEFT_MARGIN = s(14)
ALPHABET_WRAPPER_WIDTH = ALPHABET_WRAPPER_LEFT_MARGIN + ALPHABET_COLUMN_WIDTH + s(6)

LIST_ROWS_FROM_TOP = 2

# Shared content column on poster-detail screens (header + list).
LIST_CONTENT_MARGINS = (SPACE_MD, SPACE_MD, SPACE_MD, 0)
LIST_OUTER_MARGINS = LIST_CONTENT_MARGINS
LIST_VIEWPORT_MARGINS = (0, SPACE_MD, 0, SPACE_MD)
LIST_ROW_SPACING = s(16)
LIST_TEXT_PAD_LEFT = s(16)
LIST_ROW_MARGINS = (LIST_TEXT_PAD_LEFT, LIST_ROW_SPACING, LIST_ROW_SPACING, LIST_ROW_SPACING)

SIDEBAR_CONTENT_MARGINS = (s(20), s(24), s(16), s(16))
SIDEBAR_SECTION_SPACING = s(16)
SIDEBAR_MENU_ICON_SIZE = ICON_SIZE_SM
SIDEBAR_MENU_ICON_GAP = s(10)
SIDEBAR_MENU_PAD_V = s(10)
SIDEBAR_MENU_PAD_H = s(12)
SIDEBAR_MENU_ITEM_HEIGHT = SIDEBAR_MENU_PAD_V * 2 + SIDEBAR_MENU_ICON_SIZE
SIDEBAR_MENU_SPACING = SPACE_XS
SIDEBAR_SECTION_LABEL_INDENT = s(12)

HEADER_TAG_ICON_SIZE = s(12)
HEADER_TAG_PAD_LEFT = s(8)
HEADER_TAG_PAD_RIGHT = s(8)
HEADER_TAG_TEXT_PAD_LEFT = s(4)
HEADER_TAG_TEXT_PAD_V = s(2)
HEADER_TAG_ROW_MARGIN_V = s(8)

TOPBAR_FILTER_PAD_V = s(2)
